### PR TITLE
MQTT Client Update

### PR DESCRIPTION
**Pull request by KasparByrne**
- Added logging
- Added port parameter for if broker does not use default port of 1883
- Extended logger to log unhandled exceptions
- Added setup for in-script testing

### CODE REVIEW

**Comment by Candice88** [comment]
Hi Kaspar!

1. As I understand you are using HiveMQ Cloud Serverless as your broker services. Ideally with MQTT over TLS we would verify the server cert to avoid man in the middle attacks - we can do this using the tls_set() method.

2. Please ensure that credentials are not stored in plain text - we covered this in the last PR, same action would apply.

3. You’ve set up logging for uncaught exceptions with the handle_exception() function, which is a good practice. However, please ensure that sensitive details are not logged in exceptions.

Please review and I am happy to merge with actions on these, your code is good.

**Comment by Candice88** [comment]
@ben-AI-cybersec are we ok to merge this? My review only highlights best practice, not critical functionality flaws.

**Comment by KasparByrne** [comment]
Sorry been focusing down documentation the past couple of days. I will try to implement some of the recommended changes this week but may have to leave them to next trimester's team to deal with.

**Comment by Candice88** [comment]
Sure Kaspar we are monitoring these til EOD Thursday so I will check back then. The first may not be implementable due to HiveMQ restrictions, the second was covered in the last PR so we can use the same response, and the last will require review in the context of your program. Thanks!

**Pull request merged**
